### ISSUE TITLE
Roadmap for registry pruning and metadata fixing

### ISSUE THREAD

**Issue by miminar** [docker/distribution#1052]
This issue outlines incremental steps leading to fully featured garbage collection of orphaned blobs and registry's metadata fixing. Each step should be covered by at least one pull request.

It relates to #462 and responds to [this request](https://github.com/docker/distribution/pull/1032#issuecomment-144107669).

Steps:
- [ ] Expose storage API to allow for image pruning with extarnal tools (PR #1050)
- [ ] Add a `registry prune` command that allows for deletion of orphanned blobs.
- [ ] Allow to fix unlinked layers and signature links in case they are referenced by manifest. Recalculate missing/invalid signature blobs.
- [ ] Move manifest revisions to their canonical path. Manifest revisions were accidentally written to `_layers` directory in `2.1.0`.
