### ISSUE TITLE
Enhance S3 support 

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#1389]
This is an epic, and should collect all issues related to overall quality enhancement of the S3 driver:

+ More functionality/configuration:
 * [x] #1353 - Custom UA String
 * [x] #753 - Support Reduced Redundancy
   + [x] To be addressed by #1401 
 * [x] #1427 - Support ap-northeast-2 region
 * [ ] Enhanced retry logic
   + [ ] See docker/goamz#15
 * [x] ~~#943 - Remove region parameter~~
+ Credentials/Auth:
 * [x] #551 - Support for standard aws credentials files
 * [x] #1041 - Profile selection with aws credentials files
   + [x] To be addressed by #1413 
 * [x] #1199 - Better handling of blank access keys/auth mode fallback
+ Bug fixes:
 * [ ] #886 - Support files >5GB
 * [ ] #1049 - Versioning and deletion issues
 * [ ] #945 - Unknown issue writing to S3 bucket
 * [ ] #1061 - EOF when pushing large layers
+ Performance:
 * [ ] #947 - Improve catalog API performance
 * [x] #1385 - Use aws/aws-sdk-go client library
 * [x] Connection pooling
 * [x] Exponential backoff
 * [x] 20% perf gain
+ More generic driver:
 * [ ] #248 - use Cloudfront with backends other than S3
 * [x] #808 - use S3 driver for other compatible backend systems
+ Documentation:
 * [ ] #1391 - Better IAM permissions documentation
 * [ ] #1073 - Better redirect / VPC documentation
 * [ ] #1447 - Better S3 credentials documentation

**Comment by schu** [comment]
Is anybody working on "more generic driver"? aws-sdk-go seems to be very closely tied to AWS S3 (e.g. fixed list of endpoints / regions).

**Comment by RichardScothern** [comment]
A change was recently merged to support S3 compatible services: https://github.com/docker/distribution/commit/2be1b4ef4f3b489b3dcaeb21ed20ec6a641b4070

**Comment by schu** [comment]
Setting the `regionendpoint` is not enough. Both drivers (s3aws and s3goamz) accept only AWS regions for parameter `region`. Also, some S3 compatible services don't support signature v4 and aws-sdk-go doesn't support S3 v2 signatures.

**Comment by bobrik** [comment]
Yep, Ceph only got v4 signatures recently, it's not even released yet: https://github.com/ceph/ceph/pull/4943.

**Comment by RichardScothern** [comment]
@schu : Which S3 clones are you thinking of?  And what do they do with the `region` parameter?

**Comment by schu** [comment]
@RichardScothern http://pithos.io/

**Comment by RichardScothern** [comment]
@schu 
> And what do they do with the region parameter?

**Comment by BrianBland** [comment]
The region is one of the parameters used in signing S3 requests, do a regionless configuration does not make sense, but I do agree that we should support nonstandard region names if an explicit endpoint is provided. 

@RichardScothern Pithos.io region configuration can be seen here: http://pithos.io/quickstart.html?highlight=region

**Comment by sdavids13** [comment]
Ideally whatever solution that is finally implemented for the "generic driver" it would also work in the scenario where a new region comes online. That way they can specify the actual region name + the s3 endpoint url (since there won't be a mapping) with the current released artifacts rather than waiting around for a new release.

**Comment by sdavids13** [comment]
Forgot to mention there are already 5 new regions planned by Amazon: https://aws.amazon.com/about-aws/global-infrastructure/

> The AWS Cloud operates 33 Availability Zones within 12 geographic Regions around the world, with 11 more Availability Zones and 5 more Regions coming online throughout the next year.

**Comment by RichardScothern** [comment]
closing in favor of the more up-to-date #1593
