### ISSUE TITLE
Refactor package layout to support future goals

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#158]
It's that time again. We need to refactor the package layout to align with upcoming goals. Here is a short list:

- [x] Move contents of `registry` package into `registry/handlers` (#167)
- [x] Move `storagedriver` and children under the `storage/driver` package. (#167)
- [x] Move `storage` under `registry` package (#167)
- [x] Move `auth` under `registry` package (#167)
- [x] Move `api` under `registry` package (#167)
- [x] Move `client` under `registry` package (#167)
- [x] Move declarations in `services.go` and `layer.go` into `registry` package.

**Comment by stevvooe** [comment]
Closed by #170.
