### ISSUE TITLE
Sprint 13: Goal = Quality

### ISSUE THREAD

**Issue by amylindburg** [docker/distribution#296]
**Sprint 13:**  _Mar 23 - Apr 6_

**Enhancements**
- [x] Add caching for Layer.Fetch to reduce backend round trips #262
- [x] Use resumable digest #295, #290
- [x] Add option to enable logrus JSON output #286, #293

**Bugs**
- [ ] No bugsnag report triggered on 500 #101

https://github.com/docker/distribution/issues/298

**Comment by stevvooe** [comment]
@amylindburg Can we close this?

**Comment by amylindburg** [comment]
Absolutely
