### ISSUE TITLE
Sprint 13: Goal = Documentation

### ISSUE THREAD

**Issue by amylindburg** [docker/distribution#301]
**Sprint 13:** _Mar 23 - Apr 6_

**Documentation**
- [ ] Document V1 and V2 setup #83 
- [ ] V1 and V2 fig configuration #82 
- [ ] Document approach to dealing with eventual consistency #146 
- [ ] Create documentation issues #254 
- [ ] Documentation layout and proposal #135 
- [ ] Webhook Notification Examples #134
- [ ] doc: add the documentation tooling #245

**Specifications**
- [ ] create specification for digest format #246 
- [ ] Use custom media types for request and responses #96 
- [ ] doc/spec: outline manifest v2, schema version 1 #183

**Comment by bfirsh** [comment]
The crucial bits, I think:

- Installation and getting started guide
- Upgrade instructions for existing users of the registry
- Registry API 2.0 docs
- 2.0 equivalent of [Docker Image Specification](https://github.com/docker/docker/blob/master/image/spec/v1.md)

**Comment by moxiegirl** [comment]
Yesterday, I spent time installing and working through setup of v1 on Ubuntu using TLS and nginix.  I also continued reading through the remainder of the distribution docs in the GitHUb repo.  I met with Josh to go over the various methods of setting up and authentication/authorization private registry.  Working with have identified these ways running the registry:

- just start one from the command line with docker (don't expect anyone to do this as insecure)
- transport layer security 
- proxy (nginx or similar)
- application ( silly, Garant)

After speaking with Josh, it seems the vast majority of users are likely to use Nginx because it gives them basic auth and some load balancing.  This gives me a good basis in terms of end-to-end demo of what most people will want: https://medium.com/@deeeet/building-private-docker-registry-with-basic-authentication-with-self-signed-certificate-using-it-e6329085e612.  

My plan for today is:
- write a basic understanding piece with placeholders for images
- get a rough draft of the installation 

Please ping me immediately if you have any concerns.

**Comment by dmp42** [comment]
Ping :)

**Comment by stevvooe** [comment]
@moxiegirl I'm not sure if that info belongs on this ticket. This ticket is more related to the sprint goal. Could you find the right [documentation issues](https://github.com/docker/distribution/labels/documentation) for each task? That, or let's make one.

Let me know how I can help.

**Comment by moxiegirl** [comment]
@stevvooe Amy asked me to update this one in particular. I had been sending out emails. At this point, I'd prefer to write the docs rather than gig around with GitHub --- at least today.

**Comment by amylindburg** [comment]
@moxiegirl Yes -- your info is helpful -- but perhaps it belongs in  "Document V1 and V2 setup #83?"

**Comment by moxiegirl** [comment]
@amylindburg @stevvooe OK with me closing this?
