### ISSUE TITLE
Port Next-Generation Issues from docker/docker-registry

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#35]
To ensure that we aren't missing any functionality, we need to port issues from docker/docker-registry. Unfortunately, this will be a manual process but we can track it with this ticket. For issues listed here, we need to do one of the following:

1. Port the issue verbatim to this repo, linking back to the closed original.
2. Write a proposal in docker/distribution, linking back to the original in docker/docker-registry.
3. Close the original.

Here is the list of issues current tagged as next-generation:

- [x] docker/docker-registry#877  NG: move to a new repository
- [x] docker/docker-registry#817  NG: v2 must require properly formed UA string
- [x] docker/docker-registry#810  NG: Automate maintenance for AUTHORS
- [x] docker/docker-registry#804  NG: access image via immutable identifier
- [x] docker/docker-registry#791  NG: Clarify StorageDriver semantics around invalid offsets
- [x] docker/docker-registry#768  NG: engine metrics and env info report?
- [x] docker/docker-registry#765  NG: Support timeouts in StorageDriver
- [x] docker/docker-registry#763  NG: native SSL support?
- [x] docker/docker-registry#762  improve documentation on running a private registry
- [x] docker/docker-registry#761  NG: HEADable dummy endpoint?
- [x] docker/docker-registry#757  NG: registry debug tools
- [x] docker/docker-registry#743  NG: architecture
- [x] docker/docker-registry#735  The index needs a DynamoDB implementation to go with the S3 backend
- [x] docker/docker-registry#734  NG: deprecation path and client messaging
- [x] docker/docker-registry#731  NG: add tests with chars that break filesystems
- [x] docker/docker-registry#728  NG: Add tests for common path traversal attacks
- [ ] docker/docker-registry#706  Cleanup of unused images / layers
- [ ] docker/docker-registry#704  Split streaming, content-addressable storage from transactional, mutable storage
- [ ] docker/docker-registry#698  NG: quotas
- [x] docker/docker-registry#694  NG: HTTP Transport compression for Layer downloads
- [x] docker/docker-registry#691  NG: namespace restriction
- [x] docker/docker-registry#689  NG: extension: webhooks
- [ ] docker/docker-registry#688  NG: extension: metrics
- [x] docker/docker-registry#687  NG: extension: basic search functionality
- [x] docker/docker-registry#680  NG: bugsnag, new-relic, and production instrumentation
- [x] docker/docker-registry#662  NG: Image Federation
- [x] docker/docker-registry#658  NG: mirroring model
- [x] docker/docker-registry#656  NG: healthcheck endpoints
- [ ] docker/docker-registry#650  [question] How to create a btsync storage?
- [x] docker/docker-registry#648  architecture tagging
- [x] docker/docker-registry#647  NG: caching as a first class citizen
- [x] docker/docker-registry#635  NG: Logging
- [x] docker/docker-registry#627  NG: api-doc-driven model
- [x] docker/docker-registry#626  NG: Transactional storage
- [x] docker/docker-registry#622  NG: irc hands-on meetings
- [x] docker/docker-registry#613  NG: extension model
- [x] docker/docker-registry#612  Registry next generation
- [x] docker/docker-registry#598  Proposal: extensions repository
- [x] docker/docker-registry#354  service should be able to start, even when backing store is unreachable or down

**Comment by stevvooe** [comment]
Closing this out for now. Unchecked issues may remain unported here but they are still considerations.
