### ISSUE TITLE
Distribution interface refactoring plan

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#354]
Over the next few weeks, we need to make several changes to the distribution interfaces to support their role as a client to the registry.

The following is a rough list of the goals we'd like to accomplish:

- [x] Propagate `context.Context` through storage driver method calls (#264)
- [x] Incorporate changes from #193 in stages
  - [x] Refactor `distribution.Layer` to `distribution.Blob` from #193. (#519)
  - [x] Decouple manifest service from concrete manifest struct (#1268)
  - [x] Separate `TagService` from manifest service
- [x] Incorporate blob store interface into backend
- [ ] ~~Provide more flexible service instantiation~~ (not actionable from description)

Other issues may be filed to further explain details of these items.

**Comment by xiekeyang** [comment]
@stevvooe 
According to your proposal in this issue and "TODO" comment in `registry.go`, I assume you want service to be refactored as,
**ManifestService**
```go
type ManifestService interface {
    // Exists returns true if the manifest exists.
    Exists(dgst digest.Digest) (bool, error)

    // Get retrieves the identified by the digest, if it exists.
    Get(dgst digest.Digest) (*manifest.SignedManifest, error)

    // Delete removes the manifest, if it exists.
    Delete(dgst digest.Digest) error

    // Put creates or updates the manifest.
    Put(manifest *manifest.SignedManifest) error
}
```

**tagService**
```go
type tagService interface {
    // TODO(stevvooe): The methods after this message should be moved to a
    // discrete TagService, per active proposals.

    // Tags lists the tags under the named repository.
    Tags() ([]string, error)

    // ExistsByTag returns true if the manifest exists.
    ExistsByTag(tag string) (bool, error)

    // GetByTag retrieves the named manifest, if it exists.
    GetByTag(tag string) (*manifest.SignedManifest, error)
}
```

And remove `tagStore` field from `manifestStore`. Am I correct?
Thanks a lot!

**Comment by stevvooe** [comment]
@xiekeyang Yes, this is the plan. However, this plan is somewhat ordered. We first must do the `distribution.Blob` refactor then we can undertake the other parts. I am currently working on this.

**Comment by xiekeyang** [comment]
@stevvooe 
Refactor Blob Service API #519 is done. Then, do you have the plan to start refactoring what we talk above? Thanks a lot!

**Comment by stevvooe** [comment]
@xiekeyang Yes, that is the plan. We may want to decouple the manifest structure first but the ordering is not important. I'm starting this work later this week.

**Comment by xiekeyang** [comment]
@stevvooe Any `help-wanted` kind of job on refactor issues? Thanks.
