### ISSUE TITLE
Distribution client/engine integration

### ISSUE THREAD

**Issue by dmcgowan** [docker/distribution#447]
To get the distribution related code split out of the engine, distribution will need a full client implementation which is capable of registry discovery and configuration through namespace as well as provide the necessary interface implementations for the engine.

Requirements
- [x] Distribution interface refactor #193
- [x] Registry client using distribution interface #387
- [x] Registry client integration tests
- [x] Docker engine code refactor to use distribution client (see https://github.com/dmcgowan/docker/tree/use-distribution-api for WIP)
- [x] Docker V1 fallback code integrated with distribution client
- [x] Add v2 mirror capabilities (not needed if namespace spec used)

Bonus
- [ ] Distribution client package (provides interface on top of registry client and namespace)
- [ ] Namespace Specification #303 
- [ ] Namespace package and tool #344
- [ ] Distribution push/pull to blobstore interface
- [ ] Engine implementation of blobstore using existing graph

**Comment by dmcgowan** [comment]
Additional topics to discuss because they may be challenges
- Using schema 1 of the manifest, how do we support getting digests on push
- Using namespace configuration, how do we key auth credentials (does every registry in a namespace use the same credentials?)
- For existing v2 registries without namespace discovery, will pinging the endpoints be part of the discovery process?  Then the namespace resolution process must always be the source of remote endpoint URLs.

**Comment by stevvooe** [comment]
Closing this since we've done most of this. Other items aren't really in play anymore.
