### ISSUE TITLE
Sprint 17: Objective checklist

### ISSUE THREAD

**Issue by dmcgowan** [docker/distribution#567]
Derek
- [x] Distribution client automated tests
- [x] Client PR cleanup
- [ ] Namespace specification finalization
- [ ] Namespace package 
- [ ] Namespace integration into daemon
- [ ] Trust interface specification (integrate with libtrust)
